/**
 * taskSchema.ts
 *
 * Shared types and validators for Phase 2 IMPLEMENT_TASK workflow.
 *
 * Defines three core data structures:
 *   AgentTask   — the task JSON file the developer writes
 *   PlanChange  — one file edit produced by Gemini
 *   StoredPlan  — the full plan persisted to disk between Plan and Apply stages
 *
 * Validation is pure TypeScript — no external schema library.
 * If validation fails, the agent stops before calling Gemini.
 */

import { readFileSync } from "fs";
import { resolve } from "path";

// ── AgentTask ─────────────────────────────────────────────────────────────────
// Written by the developer; lives in google-dev-agent/tasks/*.json

export interface AgentTask {
  /** Unique identifier for tracing. e.g. "task-001" */
  task_id: string;

  /** Must be "IMPLEMENT_TASK" — enforced by safetyGuard */
  task_type: "IMPLEMENT_TASK";

  /** One-sentence summary shown in reports. */
  description: string;

  /**
   * Full plain-English implementation brief passed to Gemini.
   * Be specific: name functions, fields, files, and the desired behaviour.
   */
  instruction: string;

  /**
   * Files Gemini will see as context. Paths relative to repo root.
   * Can include files outside allowed_write_paths (for context only).
   */
  read_paths: string[];

  /**
   * Files Gemini is permitted to edit. Must be a subset of read_paths.
   * Each path is validated against the safety allowlist + blocklist before
   * Gemini is called. If Gemini proposes editing a file not in this list,
   * the plan is rejected.
   */
  allowed_write_paths: string[];

  /**
   * Determines which npm build commands are run after apply.
   *   "frontend"  → npm run build in repo root (Vite)
   *   "backend"   → tsc --noEmit in google-cloud-backend
   *   "both"      → backend first, then frontend
   *   "none"      → skip build (type-only changes in non-built packages)
   */
  build_target: "frontend" | "backend" | "both" | "none";

  /**
   * If true, npm run verify:backend is run after a successful build.
   * Only relevant when build_target is "backend" or "both".
   */
  run_verify: boolean;

  /** Optional extra context for Gemini (not executed — read-only briefing). */
  context?: string;
}

// ── PlanChange ────────────────────────────────────────────────────────────────
// One proposed edit produced by the Gemini planner.
// Only "edit" is supported. "create" and "delete" are Phase 3+ scope.

export interface PlanChange {
  /** Relative path from repo root. Forward slashes. */
  file_path: string;

  /** Always "edit". Any other value is rejected by the plan validator. */
  change_type: "edit";

  /** Human-readable description shown in the plan report. */
  description: string;

  /**
   * The exact substring in the current file to replace.
   * Must exist verbatim in the file before apply is permitted.
   */
  old_string: string;

  /** The string to replace old_string with. */
  new_string: string;
}

// ── StoredPlan ────────────────────────────────────────────────────────────────
// Written to reports/dev-agent/plans/<plan_id>.json after plan generation.
// Loaded by apply mode — self-contained (includes the full task).

export interface StoredPlan {
  /** Schema version. Always "2" in Phase 2. */
  plan_version: "2";

  /** e.g. "plan-20260511-143022" */
  plan_id: string;

  /** ISO timestamp when the plan was generated. */
  created_at: string;

  /** The original task (embedded so apply mode is self-contained). */
  task: AgentTask;

  /** Gemini-generated one-paragraph description of what this plan does. */
  summary: string;

  /** Ordered list of file edits. Applied top-to-bottom, all-or-nothing. */
  changes: PlanChange[];

  /**
   * Shell commands that will be run after edits are applied.
   * Derived from task.build_target — NOT generated by Gemini.
   */
  build_commands: string[];

  /** Gemini-generated commit message. Copy-pasteable by the developer. */
  suggested_commit_message: string;
}

// ── Validation ────────────────────────────────────────────────────────────────

export interface ValidationResult<T> {
  valid: boolean;
  value?: T;
  error?: string;
}

const VALID_BUILD_TARGETS = ["frontend", "backend", "both", "none"] as const;

export function validateTask(raw: unknown): ValidationResult<AgentTask> {
  if (!raw || typeof raw !== "object") {
    return { valid: false, error: "Task must be a JSON object." };
  }

  const obj = raw as Record<string, unknown>;

  // Required string fields
  for (const field of ["task_id", "task_type", "description", "instruction"] as const) {
    if (typeof obj[field] !== "string" || !(obj[field] as string).trim()) {
      return { valid: false, error: `Field "${field}" is required and must be a non-empty string.` };
    }
  }

  if ((obj.task_type as string) !== "IMPLEMENT_TASK") {
    return {
      valid: false,
      error: `"task_type" must be "IMPLEMENT_TASK". Got: "${obj.task_type}". ` +
        `For backend smoke tests use --task VERIFY_BACKEND_DEV instead.`,
    };
  }

  // Array fields
  for (const field of ["read_paths", "allowed_write_paths"] as const) {
    if (!Array.isArray(obj[field])) {
      return { valid: false, error: `Field "${field}" must be an array of file paths.` };
    }
    const arr = obj[field] as unknown[];
    if (arr.length === 0) {
      return { valid: false, error: `Field "${field}" must have at least one path.` };
    }
    for (const item of arr) {
      if (typeof item !== "string" || !item.trim()) {
        return { valid: false, error: `All items in "${field}" must be non-empty strings.` };
      }
    }
  }

  // allowed_write_paths must be a subset of read_paths
  const readSet = new Set(obj.read_paths as string[]);
  for (const wp of obj.allowed_write_paths as string[]) {
    if (!readSet.has(wp)) {
      return {
        valid: false,
        error: `"allowed_write_paths" entry "${wp}" is not in "read_paths". ` +
          `Every write path must also be a read path so Gemini sees the file content.`,
      };
    }
  }

  // build_target
  if (!VALID_BUILD_TARGETS.includes(obj.build_target as typeof VALID_BUILD_TARGETS[number])) {
    return {
      valid: false,
      error: `"build_target" must be one of: ${VALID_BUILD_TARGETS.join(", ")}. Got: "${obj.build_target}".`,
    };
  }

  // run_verify
  if (typeof obj.run_verify !== "boolean") {
    return { valid: false, error: `"run_verify" must be a boolean (true or false).` };
  }

  // optional context
  if (obj.context !== undefined && typeof obj.context !== "string") {
    return { valid: false, error: `"context" must be a string if provided.` };
  }

  // Reject auto_approve if present and truthy (it can only ever be false)
  if (obj.auto_approve === true) {
    return {
      valid: false,
      error: `"auto_approve" cannot be set to true. The plan always stops for human review. ` +
        `Remove this field or set it to false.`,
    };
  }

  return {
    valid: true,
    value: {
      task_id: (obj.task_id as string).trim(),
      task_type: "IMPLEMENT_TASK",
      description: (obj.description as string).trim(),
      instruction: (obj.instruction as string).trim(),
      read_paths: obj.read_paths as string[],
      allowed_write_paths: obj.allowed_write_paths as string[],
      build_target: obj.build_target as AgentTask["build_target"],
      run_verify: obj.run_verify as boolean,
      context: obj.context as string | undefined,
    },
  };
}

/** Load and validate a task JSON file. Throws on error. */
export function loadTask(taskFilePath: string, cwd: string): AgentTask {
  const absPath = resolve(cwd, taskFilePath);
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(absPath, "utf-8"));
  } catch (err) {
    throw new Error(`Cannot read task file "${absPath}": ${String(err)}`);
  }

  const result = validateTask(raw);
  if (!result.valid || !result.value) {
    throw new Error(`Invalid task file "${absPath}": ${result.error}`);
  }
  return result.value;
}

/** Load a stored plan JSON file. Throws on error. */
export function loadStoredPlan(planId: string, plansDir: string): StoredPlan {
  const planPath = resolve(plansDir, `${planId}.json`);
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(planPath, "utf-8"));
  } catch (err) {
    throw new Error(`Cannot read plan file "${planPath}": ${String(err)}`);
  }

  const obj = raw as Record<string, unknown>;
  if (obj.plan_version !== "2") {
    throw new Error(
      `Plan "${planId}" has version "${obj.plan_version}" but this agent requires version "2". ` +
        `Re-generate the plan with the current agent version.`
    );
  }
  return raw as StoredPlan;
}

/** Derive the npm build commands for a given build_target. */
export function buildCommandsFor(target: AgentTask["build_target"]): string[] {
  switch (target) {
    case "frontend": return ["npm:frontend-build"];
    case "backend":  return ["npm:backend-lint"];
    case "both":     return ["npm:backend-lint", "npm:frontend-build"];
    case "none":     return [];
  }
}
